# Site settings
title: Joseph's Photo Album
email: songyosub@naver.com
description: > # this means to ignore newlines until "baseurl:"
  사진 공간.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  github_username

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


